# persistent volume for postgres server
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: devops
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/kube-data/postgres"
    
# persistent volume claim for postgres server
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: devops
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi