apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: devops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.6
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
              name: port-postgres
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim