apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devops
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 30100
     protocol: TCP
     targetPort: 5432
     nodePort: 30100
     name: port-postgres
  selector:
   app: postgres